### ISSUE TITLE
Jupiterq cannot connect to the kernel

### ISSUE THREAD

**Issue by SSoltani83** [KxSystems/jupyterq#30]
I am working on Mac. q works on the terminal but when I lunch it from Jupiter notebook it is not able to connect to the kernel.

here is the error message I get:

Last login: Sat Nov  3 18:29:36 on ttys000
Skanders-Air:~ skandersoltani$ jupyter console --kernel=qpk
'2018.11.03T18:47:14.013 libpython
  [6]  /anaconda3/q/p.q:8: 
 `L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
 .p:(`:./p 2:(`init;2))[L;H]]
    ^
'2018.11.03T18:47:14.013 cleanz
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 323, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
Skanders-Air:~ skandersoltani$ jupyter console --kernel=qpk
'2018.11.03T18:54:26.859 libpython
  [6]  /anaconda3/q/p.q:8: 
 `L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
 .p:(`:./p 2:(`init;2))[L;H]]
    ^
'2018.11.03T18:54:26.859 cleanz
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 323, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request

**Comment by jhanna-kx** [comment]
It looks like there is an issue with the install of embedPy. 

Are you able to run embedPy in a q console without jupyter, i.e.

``` 
$ q p.q
...
q)p)print('embedPy runs')
```

Could you also post the versions of embedpy, jupyterq, kdb and python you are using with this command

```
conda list "embedpy|jupyterq|kdb|python"
```
Thanks

**Comment by elopezaguilera** [comment]
Closing this issue. Unable to replicate the issue without further information. Feel free to reopen with the details to replicate it.
