### ISSUE TITLE
issue starting qpk kernel

### ISSUE THREAD

**Issue by ptunz** [KxSystems/jupyterq#32]
Running on windows
fresh install of anaconda , but downgraded to 3.6 (tensorflow does not support yet)

q runs but does not load q.k (from q q.k) !- had to add q.q (with some show(s) to \l q.k

(C:\app\Anaconda3) C:\app\anaconda3\q>conda list "embedpy|jupyterq|kdb|python"
packages in environment at C:\app\Anaconda3:

 Name                    Version                   Build  Channel
embedpy                   1.3.1            py36hfa6e2cd_0    kx
ipython                   7.1.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
jupyterq                  1.1.3            py36hfa6e2cd_0    kx
kdb                       3.6                  2018.10.23    kx
msgpack-python            0.5.6            py36he980bc4_1
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.5                    py36_0

(C:\app\Anaconda3) C:\app\anaconda3\q>q
KDB+ 3.6 2018.10.23 Copyright (C) 1993-2018 Kx Systems
w64/ 12(16)core ....
"q.q started"
"loading p.k"

I get this when I try to print - python works in q but still no connection to kernel. took q.q out

(C:\app\Anaconda3) C:\Users\admin>q
KDB+ 3.6 2018.10.23 Copyright (C) 1993-2018 Kx Systems
w64/ 12(16) ...

q)\l p.q
q)print ("embedPy runs")
embedPy runs

but Kernel it times-out.... any way to debug? kernel_info_request - should print something into log...

dlls are there:
(C:\app\Anaconda3) C:\app\anaconda3\q\w64>ls -al
total 808
drwxr-xr-x 1 ... None      0 Nov 16 23:24 .
drwxr-xr-x 1 ... None      0 Nov 17 00:27 ..
-rwxr-xr-x 2 ... None 103936 Oct 12 06:00 jupyterq.dll
-rwxr-xr-x 2 ... None 120320 Sep  4 14:37 p.dll
-rwxr-xr-x 2 ... None 593408 Oct 23 13:26 q.exe

when I start kernel - do not see q process running in the process list - must be crashed. but when i start by hand it does not crashes

(C:\app\Anaconda3) C:\app\anaconda3\q>jupyter console --kernel=qpk
"q.q started"
"loading p.k"
Traceback (most recent call last):
  File "C:\app\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 341, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "C:\app\Anaconda3\lib\site-packages\jupyter_client\client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "C:\app\Anaconda3\lib\site-packages\jupyter_client\blocking\channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\app\Anaconda3\Scripts\jupyter-console-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\app\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\app\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-117>", line 2, in initialize
  File "C:\app\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\app\Anaconda3\lib\site-packages\jupyter_console\app.py", line 142, in initialize
    self.init_shell()
  File "C:\app\Anaconda3\lib\site-packages\jupyter_console\app.py", line 115, in init_shell
    confirm_exit=self.confirm_exit,
  File "C:\app\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\app\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 287, in __init__
    self.init_kernel_info()
  File "C:\app\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 344, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request

**Comment by elopezaguilera** [comment]
Hi,

What you mean with "q runs but does not load q.k (from q q.k) !- had to add q.q (with some show(s) to \l q.k"? Could you explain this better, please? q needs to load q.k in order to run so it doesn't make sense that you need to use \l q.k

Anyway, I have tried to replicate your issue using the same versions as you have installed and everything works fine for me. Could you provide us with further information so that we can try to replicate it, please?

Thanks.

**Comment by cmccarthy1** [comment]
Hi @ptunz,

Thanks for opening the issue. As we don't have enough information available at present to replicate your issue I'm going to close it for now.

Please feel free to reopen the issue if you deem it appropriate or have more information to allow us look into this further.
